// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Bun6RhmlwPSsEUgTcMeefYcx-U6s9oo',
    appId: '1:105286709079:web:6e796de3e30407f65c9812',
    messagingSenderId: '105286709079',
    projectId: 'yardimpusulasi-7f78f',
    authDomain: 'yardimpusulasi-7f78f.firebaseapp.com',
    storageBucket: 'yardimpusulasi-7f78f.firebasestorage.app',
    measurementId: 'G-11W6QMTMFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7sekgLgRag3XYTls1aXwD72s_moUD0yA',
    appId: '1:105286709079:android:a48c7458ca43bc255c9812',
    messagingSenderId: '105286709079',
    projectId: 'yardimpusulasi-7f78f',
    storageBucket: 'yardimpusulasi-7f78f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM42DnnTrolGTFTGDtEo_pLVpK7Sd203E',
    appId: '1:105286709079:ios:e441792a5f989dc25c9812',
    messagingSenderId: '105286709079',
    projectId: 'yardimpusulasi-7f78f',
    storageBucket: 'yardimpusulasi-7f78f.firebasestorage.app',
    iosBundleId: 'com.yp.yardimpusulasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM42DnnTrolGTFTGDtEo_pLVpK7Sd203E',
    appId: '1:105286709079:ios:e441792a5f989dc25c9812',
    messagingSenderId: '105286709079',
    projectId: 'yardimpusulasi-7f78f',
    storageBucket: 'yardimpusulasi-7f78f.firebasestorage.app',
    iosBundleId: 'com.yp.yardimpusulasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Bun6RhmlwPSsEUgTcMeefYcx-U6s9oo',
    appId: '1:105286709079:web:2e20f577efd7cf665c9812',
    messagingSenderId: '105286709079',
    projectId: 'yardimpusulasi-7f78f',
    authDomain: 'yardimpusulasi-7f78f.firebaseapp.com',
    storageBucket: 'yardimpusulasi-7f78f.firebasestorage.app',
    measurementId: 'G-DDGJ0X418W',
  );
}
